services:
  - type: web
    name: django-local-library01
    runtime: python
    startCommand: "gunicorn locallibrary.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://test_gcf4_user:HsOkm7Yz4ytczQ5HLNr4q11HrO3j3Uc9@dpg-cv96hrdumphs73flbk00-a/test_gcf4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.9.0
